//
//  DateExtensions.swift
//  TapWater
//
//  Created by Jonathan Hooper on 11/15/14.
//  Copyright (c) 2014 NewAperio. All rights reserved.
//

import Foundation

extension NSDate {
    
    class func fromRailsString(string: String) -> NSDate! {
        // Create a date formatter
        var dateFormatter: NSDateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZ"
        dateFormatter.locale = NSLocale(localeIdentifier: "en_US_POSIX")
        dateFormatter.timeZone = NSTimeZone(forSecondsFromGMT: 0)
        
        // Return the date loaded from the string
        return dateFormatter.dateFromString(string)
        
    }
    
    func toRailsString() -> String {
        // Create a date formatter
        var dateFormatter: NSDateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZ"
        dateFormatter.locale = NSLocale(localeIdentifier: "en_US_POSIX")
        dateFormatter.timeZone = NSTimeZone(forSecondsFromGMT: 0)
        
        // Return the string generatd by the date formatter
        return dateFormatter.stringFromDate(self)
    }
    
    func toHumanReadableString() -> String {
        // Create a date formatter
        var dateFormatter: NSDateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "MMM dd, yyyy"
        dateFormatter.timeZone = NSTimeZone.localTimeZone()
        
        // Return the string generated by the date formatter
        return dateFormatter.stringFromDate(self)
        
    }
    
    func toHumanReadableIntervalString() -> String {
        if -1 * self.timeIntervalSinceNow < 60 {
            return NSString(format: "%i sec", -1 * Int(self.timeIntervalSinceNow))
        } else if -1 * self.timeIntervalSinceNow < 60 * 60 {
            return NSString(format: "%i min", -1 * Int(self.timeIntervalSinceNow) / 60)
        } else if self.isToday() {
            return NSString(format: "%i hr", -1 * Int(self.timeIntervalSinceNow) / 3600)
        }
        
        return self.toHumanReadableString()
    }
    
    func isToday() -> Bool {
        // Create a date for 00:00:00 today
        let gregorianCalendar: NSCalendar = NSCalendar(calendarIdentifier: NSGregorianCalendar)!
        var dateComponents: NSDateComponents = gregorianCalendar.components((NSCalendarUnit.CalendarCalendarUnit | NSCalendarUnit.CalendarUnitMonth | NSCalendarUnit.CalendarUnitDay), fromDate: NSDate())
        dateComponents.hour = 0
        dateComponents.minute = 0
        dateComponents.second = 0
        let today: NSDate = gregorianCalendar.dateFromComponents(dateComponents)!
        
        // Compare this date to the date for today
        if self.timeIntervalSince1970 > today.timeIntervalSince1970 {
            return true
        } else {
            return false
        }
    }
    
    
}
